import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { apiGet } from "../api/client";
import { PageHeader, PageState, Stat } from "../components/NativeUi";

export function AnalyticsPage(){
 const [period,setPeriod]=useState("month"); const q=useQuery({queryKey:["analytics",period],queryFn:()=>apiGet<any>(`/api/v1/analytics?period=${encodeURIComponent(period)}`)});
 if(q.isPending)return <PageState title="Loading analytics" text="Building workspace trends…"/>;if(q.isError||!q.data)return <PageState title="Analytics unavailable" text="LifeOS could not load analytics." error retry={()=>q.refetch()}/>;const d=q.data,s=d.summary||{};
 return <section className="workspace-page"><PageHeader eyebrow="Workspace intelligence" title="Analytics" description="Use trends to understand execution, not to create more noise." actions={<><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="week">Week</option><option value="month">Month</option><option value="quarter">Quarter</option><option value="year">Year</option></select><a className="secondary-button" href="/api/v1/analytics/exports/tasks.csv">Export tasks</a><a className="secondary-button" href="/api/v1/analytics/exports/focus.csv">Export focus</a></>}/>
 <div className="summary-strip"><Stat label="Completed" value={s.completed_in_period??0}/><Stat label="Focus" value={s.focus_label??`${s.focus_minutes??0} min`}/><Stat label="Overdue" value={s.overdue_tasks??0}/><Stat label="Active projects" value={s.active_projects??0}/></div>
 <div className="native-two-column"><article className="panel-card"><div className="section-heading"><div><span className="panel-kicker">Task flow</span><h2>Created vs completed</h2></div></div><div className="mini-chart">{(d.task_series||[]).map((x:any,i:number)=><div className="mini-chart-column" key={i} title={x.title}><span className="mini-bar created" style={{height:`${Math.max(4,x.created_height||0)}%`}}/><span className="mini-bar completed" style={{height:`${Math.max(4,x.completed_height||0)}%`}}/><small>{x.label}</small></div>)}</div></article><article className="panel-card"><div className="section-heading"><div><span className="panel-kicker">Focus</span><h2>Focused time</h2></div></div><div className="mini-chart single">{(d.focus_series||[]).map((x:any,i:number)=><div className="mini-chart-column" key={i} title={x.title}><span className="mini-bar focus" style={{height:`${Math.max(4,x.height||0)}%`}}/><small>{x.label}</small></div>)}</div></article></div>
 <article className="panel-card"><div className="section-heading"><div><span className="panel-kicker">What stands out</span><h2>Insights</h2></div></div><div className="insight-grid">{(d.insights||[]).map((x:any,i:number)=><div className="insight-mini" key={i}><strong>{x.title||x.label||`Insight ${i+1}`}</strong><span>{x.text||x.detail||x.message||String(x)}</span></div>)}</div></article>
 <article className="panel-card"><div className="section-heading"><div><span className="panel-kicker">Projects</span><h2>Project performance</h2></div></div><div className="simple-resource-list">{(d.projects||[]).map((x:any)=><div key={x.id||x.project_id}><strong>{x.title||x.project_title}</strong><span>{x.completed_tasks??0} completed · {x.open_tasks??0} open · {x.focus_label||`${x.focus_minutes??0} min focus`}</span></div>)}</div></article>
 </section>
}
