import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { apiGet, apiPostForm, ApiError } from "../api/client";
import { EmptyState, ErrorBanner, PageHeader, PageState } from "../components/NativeUi";

type Document={id:number;project_id:number|null;project:{id:number;title:string}|null;filename:string;version_label:string;uploaded_at:string|null;has_text:boolean;summary:string|null};
type Project={id:number;title:string};type Data={items:Document[];projects:Project[];max_upload_bytes:number};
export function DocumentsPage(){const qc=useQueryClient();const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);const q=useQuery({queryKey:["documents"],queryFn:()=>apiGet<Data>("/api/v1/documents")});const upload=useMutation({mutationFn:(form:FormData)=>apiPostForm<any>("/api/v1/documents",form),onSuccess:async(r)=>{setMessage(r.indexing_succeeded?`Uploaded and indexed ${r.chunk_count} searchable chunks.`:"Uploaded. Search indexing may need attention.");await qc.invalidateQueries({queryKey:["documents"]})},onError:e=>setError(e instanceof ApiError?e.message:"Upload failed.")});if(q.isPending)return <PageState title="Opening Document Brain" text="Loading your documents…"/>;if(q.isError||!q.data)return <PageState title="Document Brain unavailable" text="Could not load documents." error retry={()=>q.refetch()}/>;const d=q.data;
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError(null);setMessage(null);upload.mutate(new FormData(e.currentTarget))}
 return <section className="workspace-page"><PageHeader eyebrow="Document Brain" title="Documents" description="Upload trusted project evidence, understand it, ask grounded questions, compare versions and turn findings into action." actions={<a href="/documents/compare" className="secondary-button">Compare documents</a>}/><ErrorBanner message={error}/>{message?<div className="form-alert success">{message}</div>:null}<article className="panel-card document-upload-card"><div className="section-heading"><div><span className="panel-kicker">Add evidence</span><h2>Upload PDF</h2></div><small>Max {Math.round(d.max_upload_bytes/1024/1024)} MB</small></div><form className="native-form-grid" onSubmit={submit}><label>Project<select name="project_id" required defaultValue=""><option value="" disabled>Select project</option>{d.projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>PDF<input type="file" name="document" accept="application/pdf,.pdf" required/></label><div className="form-actions full"><button className="primary-button" disabled={upload.isPending}>{upload.isPending?"Uploading…":"Upload document"}</button></div></form></article><div className="native-card-grid">{d.items.length?d.items.map(doc=><article className="panel-card document-card-native" key={doc.id}><div className="card-topline"><span className="status-pill">{doc.has_text?"Searchable":"Needs OCR"}</span><span>{doc.version_label}</span></div><h3><a href={`/documents/${doc.id}`}>{doc.filename}</a></h3><p>{doc.summary||"Open the document to analyze it or ask grounded questions."}</p><div className="resource-meta"><span>{doc.project?.title||"Project document"}</span><span>{doc.uploaded_at?new Date(doc.uploaded_at).toLocaleDateString():""}</span></div><a className="primary-button compact" href={`/documents/${doc.id}`}>Open document</a></article>):<EmptyState title="No documents yet" text="Upload a PDF to start building grounded project knowledge."/>}</div></section>}
