import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { apiGet, apiPost, ApiError } from "../api/client";
import { EmptyState, ErrorBanner, PageHeader, PageState, VerifyButton } from "../components/NativeUi";
import { currentPath } from "../core/navigation";

type Doc={id:number;filename:string;project_id:number|null;version_label:string};type Comparison={id:number;document_a:Doc|null;document_b:Doc|null;summary:string|null;findings:any[];status:string;error_message:string|null;created_at:string|null};
export function DocumentComparePage(){const [error,setError]=useState<string|null>(null);const q=useQuery({queryKey:["comparisons"],queryFn:()=>apiGet<{documents:Doc[];items:Comparison[]}>("/api/v1/documents/comparisons")});const compare=useMutation({mutationFn:(x:any)=>apiPost<{item:Comparison}>("/api/v1/documents/comparisons",x),onSuccess:r=>window.location.assign(`/documents/comparisons/${r.item.id}`),onError:e=>setError(e instanceof ApiError?e.message:"Comparison failed.")});if(q.isPending)return <PageState title="Loading comparison workspace" text="Loading your documents…"/>;if(q.isError||!q.data)return <PageState title="Comparison unavailable" text="Could not load document comparison." error retry={()=>q.refetch()}/>;function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);compare.mutate({document_a_id:Number(f.get('document_a_id')),document_b_id:Number(f.get('document_b_id'))})}return <section className="workspace-page"><PageHeader eyebrow="Document Brain" title="Compare documents" description="Compare two owned PDFs in a fixed A → B direction and keep only verified differences." actions={<a className="secondary-button" href="/documents">Back to documents</a>}/><ErrorBanner message={error}/><article className="panel-card"><form className="native-form-grid" onSubmit={submit}><label>Document A<select name="document_a_id" required defaultValue=""><option value="" disabled>Select first document</option>{q.data.documents.map(x=><option key={x.id} value={x.id}>{x.filename}</option>)}</select></label><label>Document B<select name="document_b_id" required defaultValue=""><option value="" disabled>Select second document</option>{q.data.documents.map(x=><option key={x.id} value={x.id}>{x.filename}</option>)}</select></label><div className="form-actions full"><button className="primary-button" disabled={compare.isPending}>{compare.isPending?"Comparing…":"Compare A → B"}</button></div></form></article><article className="panel-card"><div className="section-heading"><div><span className="panel-kicker">Saved history</span><h2>Recent comparisons</h2></div></div>{q.data.items.length?<div className="simple-resource-list">{q.data.items.map(x=><a href={`/documents/comparisons/${x.id}`} key={x.id}><strong>{x.document_a?.filename} → {x.document_b?.filename}</strong><span>{x.status} · {x.created_at?new Date(x.created_at).toLocaleString():''}</span></a>)}</div>:<EmptyState title="No comparisons yet" text="Choose two documents above to create the first verified comparison."/>}</article></section>}

export function DocumentComparisonDetailsPage(){const id=Number(currentPath().match(/^\/documents\/comparisons\/(\d+)$/)?.[1]??NaN);const qc=useQueryClient();const [error,setError]=useState<string|null>(null);const q=useQuery({queryKey:["comparison",id],queryFn:()=>apiGet<{item:Comparison;category_counts:Record<string,number>}>(`/api/v1/documents/comparisons/${id}`),enabled:Number.isFinite(id)});const rerun=useMutation({mutationFn:()=>apiPost<{item:Comparison}>(`/api/v1/documents/comparisons/${id}/rerun`),onSuccess:async()=>qc.invalidateQueries({queryKey:["comparison",id]}),onError:e=>setError(e instanceof ApiError?e.message:"Could not rerun comparison.")});if(q.isPending)return <PageState title="Opening comparison" text="Loading verified findings…"/>;if(q.isError||!q.data)return <PageState title="Comparison unavailable" text="This comparison could not be loaded." error retry={()=>q.refetch()}/>;const c=q.data.item;return <section className="workspace-page"><PageHeader eyebrow="Verified comparison" title={`${c.document_a?.filename||'Document A'} → ${c.document_b?.filename||'Document B'}`} description={c.summary||"Grounded differences between the selected documents."} actions={<><a className="secondary-button" href="/documents/compare">New comparison</a><button className="primary-button" onClick={()=>rerun.mutate()} disabled={rerun.isPending}>{rerun.isPending?"Rerunning…":"Rerun"}</button></>}/><ErrorBanner message={error}/><div className="summary-strip">{Object.entries(q.data.category_counts).map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="details-stack">{c.findings?.length?c.findings.map((x:any,i:number)=><article className="panel-card comparison-finding" key={i}><div className="section-heading"><div><span className="panel-kicker">{x.category||'Difference'}</span><h2>{x.title||x.change||`Finding ${i+1}`}</h2></div></div><p>{x.summary||x.detail||x.description||''}</p><div className="comparison-evidence"><VerifyButton source={x.source_a||x.sourceA||x.source}/><VerifyButton source={x.source_b||x.sourceB}/></div></article>):<EmptyState title="No verified findings" text="The comparison did not produce evidence-backed differences."/>}</div></section>}
