import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { apiGet, apiPost, ApiError } from "../api/client";
import { EmptyState, ErrorBanner, PageHeader, PageState, Stat } from "../components/NativeUi";

type Task={id:number;title:string;project:{id:number;title:string}|null;deadline:string|null;importance:string};
type Distraction={id:number;content:string;captured_at:string|null;converted_task_id:number|null};
type Session={id:number;task_id:number|null;task:{id:number;title:string}|null;title:string;goal:string|null;planned_minutes:number;actual_minutes:number;elapsed_seconds:number;status:string;distraction_count:number;distractions:Distraction[]};
type FocusData={tasks:Task[];active_session:Session|null;elapsed_seconds:number;today_minutes:number};

function formatTimer(seconds:number){const m=Math.floor(seconds/60);const s=seconds%60;return `${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
export function FocusPage(){
 const qc=useQueryClient();const [error,setError]=useState<string|null>(null);const query=useQuery({queryKey:["focus"],queryFn:()=>apiGet<FocusData>("/api/v1/focus"),refetchInterval:30_000});const refresh=()=>qc.invalidateQueries({queryKey:["focus"]});
 const [clock,setClock]=useState(0);useEffect(()=>{setClock(query.data?.elapsed_seconds||0)},[query.data?.elapsed_seconds]);useEffect(()=>{if(query.data?.active_session?.status!=="running")return;const id=setInterval(()=>setClock(v=>v+1),1000);return()=>clearInterval(id)},[query.data?.active_session?.status]);
 const action=(path:string,body?:unknown)=>apiPost(path,body);const start=useMutation({mutationFn:(x:any)=>action("/api/v1/focus/start",x),onSuccess:refresh,onError:e=>setError(e instanceof ApiError?e.message:"Could not start focus.")});const simple=useMutation({mutationFn:({path,body}:{path:string;body?:unknown})=>action(path,body),onSuccess:refresh,onError:e=>setError(e instanceof ApiError?e.message:"Focus action failed.")});
 if(query.isPending)return <PageState title="Opening Focus" text="Preparing your session…"/>;if(query.isError||!query.data)return <PageState title="Focus unavailable" text="LifeOS could not load Focus Mode." error retry={()=>query.refetch()}/>;const d=query.data,s=d.active_session;
 function submitStart(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);start.mutate({task_id:f.get("task_id")||null,duration:Number(f.get("duration")||25),goal:String(f.get("goal")||"")})}
 function addDistraction(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!s)return;const f=new FormData(e.currentTarget);simple.mutate({path:`/api/v1/focus/${s.id}/distractions`,body:{content:String(f.get("content")||"")}});e.currentTarget.reset()}
 return <section className="workspace-page focus-native"><PageHeader eyebrow="Deep work" title="Focus Mode" description="Protect one meaningful block of work, capture distractions, and review the result." actions={<a className="secondary-button" href="/focus/insights">Focus insights</a>}/><ErrorBanner message={error}/>
 <div className="summary-strip"><Stat label="Focused today" value={`${d.today_minutes} min`}/><Stat label="Available tasks" value={d.tasks.length}/><Stat label="Session" value={s?s.status:"Ready"}/></div>
 {!s?<article className="panel-card focus-start-card"><div className="section-heading"><div><span className="panel-kicker">Start a block</span><h2>What are you focusing on?</h2></div></div><form className="native-form-grid" onSubmit={submitStart}><label>Task<select name="task_id"><option value="">Free focus session</option>{d.tasks.map(t=><option key={t.id} value={t.id}>{t.title}{t.project?` — ${t.project.title}`:""}</option>)}</select></label><label>Duration<select name="duration" defaultValue="25"><option value="15">15 minutes</option><option value="25">25 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label><label className="full">Goal<input name="goal" placeholder="What must be true when this session ends?"/></label><div className="form-actions full"><button className="primary-button">Start focus</button></div></form></article>:
 <div className="focus-layout-native"><article className="panel-card focus-session-card"><span className="panel-kicker">{s.status}</span><h2>{s.title}</h2><div className="focus-clock">{formatTimer(clock)}</div><p>{s.goal||"Stay with the selected work until the session ends."}</p><div className="hero-actions">{s.status==="running"?<button className="secondary-button" onClick={()=>simple.mutate({path:`/api/v1/focus/${s.id}/pause`})}>Pause</button>:<button className="primary-button" onClick={()=>simple.mutate({path:`/api/v1/focus/${s.id}/resume`})}>Resume</button>}<button className="secondary-button" onClick={()=>simple.mutate({path:`/api/v1/focus/${s.id}/extend`})}>+ Extend</button><button className="primary-button" onClick={()=>simple.mutate({path:`/api/v1/focus/${s.id}/finish`,body:{goal_result:"full",focus_rating:4,notes:"",complete_task:false}})}>Finish</button><button className="danger-button" onClick={()=>confirm("Cancel this session?")&&simple.mutate({path:`/api/v1/focus/${s.id}/cancel`})}>Cancel</button></div></article><article className="panel-card"><div className="section-heading"><div><span className="panel-kicker">Parking lot</span><h2>Distractions</h2></div></div><form className="ask-row" onSubmit={addDistraction}><input name="content" placeholder="Capture it and return to focus"/><button className="secondary-button">Save</button></form>{s.distractions?.length?s.distractions.map(x=><div className="resource-row" key={x.id}><span>{x.content}</span>{!x.converted_task_id?<button className="secondary-button compact" onClick={()=>simple.mutate({path:`/api/v1/focus/distractions/${x.id}/convert`})}>Make task</button>:<small>Task created</small>}</div>):<EmptyState title="No distractions captured" text="If something pulls your attention, park it here."/>}</article></div>}
 </section>
}

export function FocusInsightsPage(){const q=useQuery({queryKey:["focus-insights"],queryFn:()=>apiGet<any>("/api/v1/focus/insights")});if(q.isPending)return <PageState title="Loading insights" text="Reviewing your focus history…"/>;if(q.isError||!q.data)return <PageState title="Insights unavailable" text="Could not load focus insights." error retry={()=>q.refetch()}/>;const d=q.data;return <section className="workspace-page"><PageHeader eyebrow="Focus intelligence" title="Focus insights" description="See patterns from completed sessions without turning the dashboard into a scoreboard." actions={<a className="secondary-button" href="/focus">Back to Focus</a>}/><div className="summary-strip"><Stat label="This week" value={d.week_minutes??0} hint="focused minutes"/><Stat label="Sessions" value={d.week_sessions?.length??d.week_session_count??0}/><Stat label="Distractions" value={d.week_distractions??0}/></div><article className="panel-card json-friendly"><h2>Patterns</h2>{(d.insights||d.patterns||[]).length?(d.insights||d.patterns).map((x:any,i:number)=><div className="insight-mini" key={i}><strong>{x.title||x.label||`Insight ${i+1}`}</strong><span>{x.text||x.message||x.detail||String(x)}</span></div>):<p className="muted-copy">Complete more sessions to build useful focus patterns.</p>}</article></section>}
