import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { apiGet, apiPost, ApiError } from "../api/client";
import { EmptyState, ErrorBanner, PageHeader, PageState } from "../components/NativeUi";
import { currentPath } from "../core/navigation";
import { ContextConnectionsPanel } from "../components/ContextConnectionsPanel";

type Suggestion={id:number;title:string;description:string|null;priority:string;deadline:string|null;status:string;created_task_id:number|null};
type Question={id:number;question:string;answer:string|null;status:string;error_message:string|null;created_at:string|null};
type Details={note:{id:number;title:string;content:string;note_type:string;project:{id:number;title:string}|null;is_pinned:boolean};latest_analysis:{id:number;status:string;summary:string|null;insights:any;error_message:string|null}|null;latest_failed_analysis:any;task_suggestions:Suggestion[];question_history:Question[];insights:any;project_context:any;analysis_is_stale:boolean};
export function NoteDetailsPage(){
 const id=Number(currentPath().match(/^\/notes\/(\d+)$/)?.[1]??NaN); const client=useQueryClient();const [error,setError]=useState<string|null>(null); const query=useQuery({queryKey:["note",id],queryFn:()=>apiGet<Details>(`/api/v1/notes/${id}`),enabled:Number.isFinite(id)}); const refresh=()=>client.invalidateQueries({queryKey:["note",id]});
 const analyze=useMutation({mutationFn:()=>apiPost<Details>(`/api/v1/notes/${id}/analyze`),onSuccess:refresh,onError:e=>setError(e instanceof ApiError?e.message:"Analysis failed.")});
 const ask=useMutation({mutationFn:(question:string)=>apiPost<{item:Question}>(`/api/v1/notes/${id}/ask`,{question}),onSuccess:refresh,onError:e=>setError(e instanceof ApiError?e.message:"LifeOS could not answer.")});
 const approve=useMutation({mutationFn:(sid:number)=>apiPost(`/api/v1/notes/${id}/suggestions/${sid}/approve`),onSuccess:refresh}); const reject=useMutation({mutationFn:(sid:number)=>apiPost(`/api/v1/notes/${id}/suggestions/${sid}/reject`),onSuccess:refresh});
 if(query.isPending)return <PageState title="Opening note" text="Loading note context…"/>; if(query.isError||!query.data)return <PageState title="Note unavailable" text="This note could not be loaded." error retry={()=>query.refetch()}/>; const d=query.data; const insights=d.insights||{};
 function submitAsk(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const q=String(f.get("question")||"").trim();if(q)ask.mutate(q)}
 return <section className="workspace-page"><div className="breadcrumbs"><a href="/notes">Notes</a><span>/</span><strong>{d.note.title}</strong></div><PageHeader eyebrow={d.note.note_type} title={d.note.title} description={d.note.project?`Linked to ${d.note.project.title}`:"General workspace"} actions={<button className="primary-button" onClick={()=>analyze.mutate()} disabled={analyze.isPending}>{analyze.isPending?"Analyzing…":d.latest_analysis?"Analyze again":"Analyze with AI"}</button>}/><ErrorBanner message={error}/>
 <article className="panel-card prose-card"><p>{d.note.content}</p></article>
 {d.latest_analysis?<article className="panel-card"><div className="section-heading"><div><span className="panel-kicker">LifeOS insight</span><h2>{insights.headline||"Analysis"}</h2></div>{d.analysis_is_stale?<span className="warning-pill">Needs refresh</span>:<span className="success-pill">Current</span>}</div><p className="lead-small">{insights.overview||d.latest_analysis.summary}</p>{insights.recommended_next_step?<div className="attention-card"><strong>Recommended next step</strong><p>{typeof insights.recommended_next_step==="string"?insights.recommended_next_step:insights.recommended_next_step.text||insights.recommended_next_step.title}</p></div>:null}<div className="insight-grid">{(insights.key_points||[]).slice(0,8).map((x:any,i:number)=><div className="insight-mini" key={i}><strong>{x.title||`Key point ${i+1}`}</strong><span>{x.detail||x.text||String(x)}</span></div>)}</div></article>:<EmptyState title="No AI analysis yet" text="Analyze the note to extract useful context, risks and next steps."/>}
 <article className="panel-card"><div className="section-heading"><div><span className="panel-kicker">Suggested work</span><h2>Task suggestions</h2></div></div>{d.task_suggestions.length?d.task_suggestions.map(x=><div className="task-line" key={x.id}><div className="task-line-main"><strong>{x.title}</strong><span>{x.description||"Suggested from this note"}</span></div><span className="importance-pill">{x.priority}</span><span className="status-pill">{x.status}</span>{x.status==="Pending"?<div className="row-actions"><button className="primary-button compact" onClick={()=>approve.mutate(x.id)}>Create task</button><button className="secondary-button compact" onClick={()=>reject.mutate(x.id)}>Ignore</button></div>:null}</div>):<EmptyState title="No suggestions" text="Actionable suggestions appear here after analysis."/>}</article>
 <ContextConnectionsPanel resourceType="note" resourceId={id} />
 <article className="panel-card"><div className="section-heading"><div><span className="panel-kicker">Ask LifeOS</span><h2>Ask about this note</h2></div></div><form className="ask-row" onSubmit={submitAsk}><input name="question" placeholder="What should I do next?" maxLength={2000}/><button className="primary-button" disabled={ask.isPending}>{ask.isPending?"Thinking…":"Ask"}</button></form><div className="qa-history">{d.question_history.map(x=><article className="qa-card" key={x.id}><strong>{x.question}</strong><p>{x.answer||x.error_message||"No answer saved."}</p></article>)}</div></article>
 </section>
}
