import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { useEffect,useMemo,useState } from "react";
import { Icon, Modal, PageSkeleton } from "../components/VSpaceUi";
import { ApiError } from "../api/client";
import type { ProjectCard,ProjectInput } from "../api/types";
import { ProjectForm } from "../features/projects/ProjectForm";
import { createProject,fetchProjects,projectKeys } from "../features/projects/api";

function formatDate(value:string|null,withYear=true){if(!value)return"";const [y,m,d]=value.split("-").map(Number);return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",...(withYear?{year:"numeric" as const}:{})}).format(new Date(y,m-1,d))}
function truncate(v:string,max=170){if(v.length<=max)return v;const c=v.slice(0,max-3),b=c.lastIndexOf(" ");return`${(b>c.length*.6?c.slice(0,b):c).trimEnd()}...`}
function slug(v:string){return v.toLowerCase().replace(/\s+/g,"-")}
function Card({card}:{card:ProjectCard}){const summary=card.goal||card.description||"No project goal has been added yet.";const tone=card.health?.tone||"neutral";return <article className="project-studio-card"><div className="project-studio-card-topline"><div className="project-studio-card-identity"><span className="project-studio-avatar">{card.title.charAt(0).toUpperCase()}</span><div><span className="workspace-eyebrow">{card.project_type||"Project"}</span><h3><a href={`/projects/${card.id}`}>{card.title}</a></h3></div></div><span className={`project-health-pill project-health-${tone}`}>{card.health?.label||"On track"}</span></div><p className="project-studio-card-summary">{truncate(summary)}</p><div className="project-studio-progress-row"><div><span>Execution progress</span><strong>{card.task_progress}%</strong></div><div className="professional-progress-track"><div className="professional-progress-fill" style={{width:`${card.task_progress}%`}}/></div></div><div className="project-studio-signal-row"><span><strong>{card.open_tasks}</strong> open tasks</span><span><strong>{card.note_count}</strong> notes</span><span>{card.deadline?`Due ${formatDate(card.deadline)}`:"No project deadline"}</span></div><div className="project-studio-health-copy"><span>Current signal</span><p>{card.health?.message||"No urgent project signal detected."}</p></div><div className="project-studio-next-action"><span>Next action</span>{card.next_task?<><strong>{card.next_task.title}</strong><small>{card.next_task.status} · {card.next_task.importance||"Medium"} priority{card.next_task.deadline?` · Due ${formatDate(card.next_task.deadline,false)}`:""}</small></>:<><strong>{card.status==="Completed"?"Project complete":"Add the first actionable task"}</strong><small>{card.status==="Completed"?"No unfinished tasks remain.":"Turn the project goal into a clear next step."}</small></>}</div><div className="project-studio-card-footer"><div className="project-studio-badges"><span className={`project-status-badge project-status-${slug(card.status||"In Progress")}`}>{card.status}</span><span className={`project-priority-badge project-priority-${(card.priority||"Medium").toLowerCase()}`}>{card.priority}</span></div><a href={`/projects/${card.id}`} className="workspace-primary-button project-studio-open-button">Open Project</a></div></article>}

export function ProjectsPage(){const [view,setView]=useState<"grid"|"list">("grid");const qc=useQueryClient();const [open,setOpen]=useState(false),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[priority,setPriority]=useState("all"),[error,setError]=useState<string|null>(null);const q=useQuery({queryKey:projectKeys.all,queryFn:fetchProjects,retry:false});
 useEffect(()=>{if(window.location.hash==="#new-project")setOpen(true)},[]);
 const create=useMutation({mutationFn:createProject,onSuccess:async()=>{setOpen(false);setError(null);history.replaceState(null,"",window.location.pathname);await Promise.all([qc.invalidateQueries({queryKey:projectKeys.all}),qc.invalidateQueries({queryKey:["dashboard"]})])},onError:e=>setError(e instanceof ApiError?e.message:"The project could not be created.")});
 const filtered=useMemo(()=>{const items=q.data?.items??[],n=search.trim().toLowerCase();return items.filter(c=>{const h=[c.title,c.goal,c.description,c.tech_stack,c.current_phase,c.project_type].filter(Boolean).join(" ").toLowerCase();return(!n||h.includes(n))&&(status==="all"||c.status.toLowerCase()===status)&&(priority==="all"||c.priority.toLowerCase()===priority)})},[q.data?.items,search,status,priority]);
 if(q.isPending)return <PageSkeleton label="Loading your projects…"/>;
 if(q.isError||!q.data)return <div className="professional-task-empty-state"><span className="empty-task-symbol">!</span><h3>Projects unavailable</h3><p>V-SPACE could not load your projects.</p><button className="workspace-secondary-button" onClick={()=>q.refetch()}>Try again</button></div>;
 const data=q.data;return <div className="projects-page project-studio-index"><header className="workspace-page-header project-studio-index-header"><div><span className="workspace-eyebrow">Project workspace</span><h1>Projects</h1><p>Everything you’re building, with a clear next step.</p></div><button type="button" className="workspace-primary-button" onClick={()=>{setOpen(true);setError(null)}}><Icon name="plus"/>New Project</button></header>
 <section className="project-studio-summary" aria-label="Project summary"><article><span>Active projects</span><strong>{data.counts.active}</strong><small>Currently moving</small></article><article><span>Need attention</span><strong>{data.counts.attention}</strong><small>Overdue, blocked, or close to deadline</small></article><article><span>Completed</span><strong>{data.counts.completed}</strong><small>Finished workspaces</small></article></section>
 {data.items.length?<><section className="project-filter-panel project-studio-filter"><div className="project-search-wrapper"><span className="project-search-icon">⌕</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search projects, goals, technologies, or phases..."/></div><div className="project-filter-controls"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="planning">Planning</option><option value="in progress">In Progress</option><option value="paused">Paused</option><option value="completed">Completed</option></select><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="all">All priorities</option><option value="low">Low Priority</option><option value="medium">Medium Priority</option><option value="high">High Priority</option><option value="critical">Critical Priority</option></select><button type="button" className="clear-project-filters" onClick={()=>{setSearch("");setStatus("all");setPriority("all")}}>Clear</button></div></section><div className="project-results-header project-studio-results-heading"><div><span className="workspace-eyebrow">Your workspaces</span><h2>Projects</h2><p>{filtered.length} visible</p></div><div className="vs-view-switch" aria-label="Project view"><button type="button" aria-label="Grid view" aria-pressed={view==="grid"} className={view==="grid"?"active":""} onClick={()=>setView("grid")}><Icon name="grid"/></button><button type="button" aria-label="List view" aria-pressed={view==="list"} className={view==="list"?"active":""} onClick={()=>setView("list")}><Icon name="list"/></button></div></div>{filtered.length?<section className={`project-studio-grid ${view==="list"?"vs-project-list":""}`}>{filtered.map(c=><Card card={c} key={c.id}/>)}</section>:<div className="task-no-results project-studio-no-results"><p>No projects match these filters.</p><button className="workspace-secondary-button" onClick={()=>{setSearch("");setStatus("all");setPriority("all")}}>Clear filters</button></div>}</>:<div className="professional-task-empty-state project-studio-empty-state"><span className="empty-task-symbol">P</span><h3>Your first project starts here.</h3><p>Connect goals, tasks, notes, documents, and progress in one place.</p><button className="workspace-primary-button" onClick={()=>setOpen(true)}>+ Create first project</button></div>}
 {open?<Modal title="Create Project" busy={create.isPending} onClose={()=>setOpen(false)}>{error?<div className="form-alert error" role="alert">{error}</div>:null}<ProjectForm submitLabel="Create Project" busy={create.isPending} onSubmit={(input:ProjectInput)=>{create.mutate(input)}} onCancel={()=>setOpen(false)}/></Modal>:null}
 </div>}
