"""add document AI analyses

Revision ID: a8b091766b1f
Revises: 20260726_0001
Create Date: 2026-07-29 15:24:49.559236
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql


revision = 'a8b091766b1f'
down_revision = '20260726_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_ai_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Unicode(length=30), nullable=False),
    sa.Column('model', sa.Unicode(length=100), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('document_type', sa.Unicode(length=80), nullable=True),
    sa.Column('summary', sa.UnicodeText(), nullable=True),
    sa.Column('insights_json', sa.UnicodeText(), nullable=True),
    sa.Column('source_fingerprint', sa.Unicode(length=64), nullable=True),
    sa.Column('error_message', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_ai_analyses_document_id'), 'document_ai_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_ai_analyses_user_id'), 'document_ai_analyses', ['user_id'], unique=False)
    op.drop_table('focus_preferences')
    op.drop_table('notes_legacy_phase6')
    op.drop_index(op.f('IX_focus_chat_session'), table_name='focus_chat_messages')
    op.drop_table('focus_chat_messages')
    op.alter_column('ai_task_suggestions', 'priority',
               existing_type=sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_task_suggestions', 'status',
               existing_type=sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_task_suggestions', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('ai_task_suggestions', 'updated_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('IX_ai_task_suggestions_analysis_id'), table_name='ai_task_suggestions')
    op.drop_index(op.f('IX_ai_task_suggestions_analysis_status'), table_name='ai_task_suggestions')
    op.drop_index(op.f('IX_ai_task_suggestions_note_id'), table_name='ai_task_suggestions')
    op.create_index(op.f('ix_ai_task_suggestions_analysis_id'), 'ai_task_suggestions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_task_suggestions_created_task_id'), 'ai_task_suggestions', ['created_task_id'], unique=False)
    op.create_index(op.f('ix_ai_task_suggestions_note_id'), 'ai_task_suggestions', ['note_id'], unique=False)
    op.alter_column('email_notification_logs', 'status',
               existing_type=sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('email_notification_logs', 'sent_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('IX_email_notification_logs_project_id'), table_name='email_notification_logs')
    op.drop_index(op.f('IX_email_notification_logs_task_id'), table_name='email_notification_logs')
    op.drop_index(op.f('IX_email_notification_logs_user_id'), table_name='email_notification_logs')
    op.create_index(op.f('ix_email_notification_logs_project_id'), 'email_notification_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_email_notification_logs_task_id'), 'email_notification_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_email_notification_logs_unique_key'), 'email_notification_logs', ['unique_key'], unique=True)
    op.create_index(op.f('ix_email_notification_logs_user_id'), 'email_notification_logs', ['user_id'], unique=False)
    op.alter_column('focus_distractions', 'captured_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('IX_focus_distraction_session'), table_name='focus_distractions')
    op.drop_index(op.f('IX_focus_distractions_converted_task_id'), table_name='focus_distractions')
    op.drop_index(op.f('IX_focus_distractions_session_id'), table_name='focus_distractions')
    op.drop_index(op.f('IX_focus_distractions_user_id'), table_name='focus_distractions')
    op.create_index(op.f('ix_focus_distractions_converted_task_id'), 'focus_distractions', ['converted_task_id'], unique=False)
    op.create_index(op.f('ix_focus_distractions_session_id'), 'focus_distractions', ['session_id'], unique=False)
    op.create_index(op.f('ix_focus_distractions_user_id'), 'focus_distractions', ['user_id'], unique=False)
    op.drop_constraint(op.f('FK_focus_distractions_session'), 'focus_distractions', type_='foreignkey')
    op.drop_constraint(op.f('FK_focus_distractions_task'), 'focus_distractions', type_='foreignkey')
    op.create_foreign_key(None, 'focus_distractions', 'focus_sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'focus_distractions', 'tasks', ['converted_task_id'], ['id'])
    op.alter_column('focus_sessions', 'planned_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('focus_sessions', 'actual_minutes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('focus_sessions', 'elapsed_seconds',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('focus_sessions', 'status',
               existing_type=sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('focus_sessions', 'distraction_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('focus_sessions', 'started_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'completed_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('IX_focus_sessions_status'), table_name='focus_sessions')
    op.drop_index(op.f('IX_focus_sessions_task_id'), table_name='focus_sessions')
    op.drop_index(op.f('IX_focus_sessions_user_id'), table_name='focus_sessions')
    op.create_index(op.f('ix_focus_sessions_status'), 'focus_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_focus_sessions_task_id'), 'focus_sessions', ['task_id'], unique=False)
    op.create_index(op.f('ix_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    op.drop_column('focus_sessions', 'ambient_sound')
    op.drop_column('focus_sessions', 'current_cycle')
    op.drop_column('focus_sessions', 'completed_cycles')
    op.drop_column('focus_sessions', 'auto_start_focus')
    op.drop_column('focus_sessions', 'energy_rating')
    op.drop_column('focus_sessions', 'auto_start_breaks')
    op.drop_column('focus_sessions', 'planned_cycles')
    op.drop_column('focus_sessions', 'focus_method')
    op.drop_column('focus_sessions', 'break_minutes')
    op.drop_column('focus_sessions', 'difficulty_rating')
    op.drop_column('focus_sessions', 'phase_elapsed_seconds')
    op.drop_column('focus_sessions', 'phase_started_at')
    op.drop_column('focus_sessions', 'ambient_theme')
    op.drop_column('focus_sessions', 'current_phase')
    op.alter_column('note_ai_analyses', 'status',
               existing_type=sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('note_ai_analyses', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('IX_note_ai_analyses_note'), table_name='note_ai_analyses')
    op.drop_index(op.f('IX_note_ai_analyses_note_id'), table_name='note_ai_analyses')
    op.drop_index(op.f('IX_note_ai_analyses_user_id'), table_name='note_ai_analyses')
    op.create_index(op.f('ix_note_ai_analyses_note_id'), 'note_ai_analyses', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_ai_analyses_user_id'), 'note_ai_analyses', ['user_id'], unique=False)
    op.alter_column('note_ai_questions', 'status',
               existing_type=sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('note_ai_questions', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('IX_note_ai_questions_created_at'), table_name='note_ai_questions')
    op.drop_index(op.f('IX_note_ai_questions_note_id'), table_name='note_ai_questions')
    op.drop_index(op.f('IX_note_ai_questions_user_id'), table_name='note_ai_questions')
    op.create_index(op.f('ix_note_ai_questions_analysis_id'), 'note_ai_questions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_note_ai_questions_note_id'), 'note_ai_questions', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_ai_questions_user_id'), 'note_ai_questions', ['user_id'], unique=False)
    op.alter_column('notes', 'note_type',
               existing_type=sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'is_pinned',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notes', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('notes', 'updated_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('IX_notes_project'), table_name='notes')
    op.drop_index(op.f('IX_notes_project_id'), table_name='notes')
    op.drop_index(op.f('IX_notes_updated_at'), table_name='notes')
    op.drop_index(op.f('IX_notes_user_id'), table_name='notes')
    op.drop_index(op.f('IX_notes_user_pinned'), table_name='notes')
    op.drop_index(op.f('IX_notes_user_updated'), table_name='notes')
    op.create_index(op.f('ix_notes_project_id'), 'notes', ['project_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.alter_column('notification_preferences', 'email_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'task_reminders_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'custom_task_reminders_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'overdue_alerts_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'project_deadline_alerts_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'project_risk_alerts_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'daily_checkup_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'weekly_summary_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'monthly_analytics_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'task_reminder_days_before',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'project_reminder_days_before',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'daily_checkup_time',
               existing_type=mssql.TIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'weekly_summary_day',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'weekly_summary_time',
               existing_type=mssql.TIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'monthly_report_day',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'monthly_report_time',
               existing_type=mssql.TIME(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('notification_preferences', 'created_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'updated_at',
               existing_type=mssql.DATETIME2(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.drop_index(op.f('IX_projects_user_id'), table_name='projects')
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.alter_column('tasks', 'reminder_enabled',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'reminder_type',
               existing_type=sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'reminder_datetime',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tasks', 'last_reminder_sent_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tasks', 'is_recurring',
               existing_type=mssql.BIT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'recurrence_type',
               existing_type=sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'recurrence_interval',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'last_generated_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('IX_tasks_completed_at'), table_name='tasks')
    op.drop_index(op.f('IX_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('IX_tasks_recurrence_parent_id'), table_name='tasks')
    op.drop_index(op.f('IX_tasks_recurrence_series_id'), table_name='tasks')
    op.drop_index(op.f('IX_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_completed_at'), 'tasks', ['completed_at'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_recurrence_parent_id'), 'tasks', ['recurrence_parent_id'], unique=False)
    op.create_index(op.f('ix_tasks_recurrence_series_id'), 'tasks', ['recurrence_series_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(getutcdate())'),
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_recurrence_series_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_recurrence_parent_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_completed_at'), table_name='tasks')
    op.create_index(op.f('IX_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('IX_tasks_recurrence_series_id'), 'tasks', ['recurrence_series_id'], unique=False)
    op.create_index(op.f('IX_tasks_recurrence_parent_id'), 'tasks', ['recurrence_parent_id'], unique=False)
    op.create_index(op.f('IX_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('IX_tasks_completed_at'), 'tasks', ['completed_at'], unique=False)
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('tasks', 'last_generated_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('tasks', 'recurrence_interval',
               existing_type=sa.INTEGER(),
               server_default=sa.text('((1))'),
               existing_nullable=False)
    op.alter_column('tasks', 'recurrence_type',
               existing_type=sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'),
               server_default=sa.text("('none')"),
               existing_nullable=False)
    op.alter_column('tasks', 'is_recurring',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    op.alter_column('tasks', 'last_reminder_sent_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('tasks', 'reminder_datetime',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('tasks', 'reminder_type',
               existing_type=sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'),
               server_default=sa.text("('none')"),
               existing_nullable=False)
    op.alter_column('tasks', 'reminder_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.create_index(op.f('IX_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.alter_column('notification_preferences', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysutcdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysutcdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'monthly_report_time',
               existing_type=mssql.TIME(),
               server_default=sa.text("('08:00')"),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'monthly_report_day',
               existing_type=sa.INTEGER(),
               server_default=sa.text('((1))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'weekly_summary_time',
               existing_type=mssql.TIME(),
               server_default=sa.text("('18:00')"),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'weekly_summary_day',
               existing_type=sa.INTEGER(),
               server_default=sa.text('((6))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'daily_checkup_time',
               existing_type=mssql.TIME(),
               server_default=sa.text("('08:00')"),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'project_reminder_days_before',
               existing_type=sa.INTEGER(),
               server_default=sa.text('((3))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'task_reminder_days_before',
               existing_type=sa.INTEGER(),
               server_default=sa.text('((1))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'monthly_analytics_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'weekly_summary_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'daily_checkup_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'project_risk_alerts_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((1))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'project_deadline_alerts_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((1))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'overdue_alerts_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((1))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'custom_task_reminders_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((1))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'task_reminders_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((1))'),
               existing_nullable=False)
    op.alter_column('notification_preferences', 'email_enabled',
               existing_type=mssql.BIT(),
               server_default=sa.text('((1))'),
               existing_nullable=False)
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_project_id'), table_name='notes')
    op.create_index(op.f('IX_notes_user_updated'), 'notes', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('IX_notes_user_pinned'), 'notes', ['user_id', 'is_pinned'], unique=False)
    op.create_index(op.f('IX_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_index(op.f('IX_notes_updated_at'), 'notes', ['updated_at'], unique=False)
    op.create_index(op.f('IX_notes_project_id'), 'notes', ['project_id'], unique=False)
    op.create_index(op.f('IX_notes_project'), 'notes', ['project_id'], unique=False)
    op.alter_column('notes', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('notes', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('notes', 'is_pinned',
               existing_type=mssql.BIT(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    op.alter_column('notes', 'note_type',
               existing_type=sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'),
               server_default=sa.text("('Quick Note')"),
               existing_nullable=False)
    op.drop_index(op.f('ix_note_ai_questions_user_id'), table_name='note_ai_questions')
    op.drop_index(op.f('ix_note_ai_questions_note_id'), table_name='note_ai_questions')
    op.drop_index(op.f('ix_note_ai_questions_analysis_id'), table_name='note_ai_questions')
    op.create_index(op.f('IX_note_ai_questions_user_id'), 'note_ai_questions', ['user_id'], unique=False)
    op.create_index(op.f('IX_note_ai_questions_note_id'), 'note_ai_questions', ['note_id'], unique=False)
    op.create_index(op.f('IX_note_ai_questions_created_at'), 'note_ai_questions', ['created_at'], unique=False)
    op.alter_column('note_ai_questions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysutcdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('note_ai_questions', 'status',
               existing_type=sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'),
               server_default=sa.text("('Completed')"),
               existing_nullable=False)
    op.drop_index(op.f('ix_note_ai_analyses_user_id'), table_name='note_ai_analyses')
    op.drop_index(op.f('ix_note_ai_analyses_note_id'), table_name='note_ai_analyses')
    op.create_index(op.f('IX_note_ai_analyses_user_id'), 'note_ai_analyses', ['user_id'], unique=False)
    op.create_index(op.f('IX_note_ai_analyses_note_id'), 'note_ai_analyses', ['note_id'], unique=False)
    op.create_index(op.f('IX_note_ai_analyses_note'), 'note_ai_analyses', ['note_id', 'created_at'], unique=False)
    op.alter_column('note_ai_analyses', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('note_ai_analyses', 'status',
               existing_type=sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'),
               server_default=sa.text("('Completed')"),
               existing_nullable=False)
    op.add_column('focus_sessions', sa.Column('current_phase', sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'), server_default=sa.text("('focus')"), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('ambient_theme', sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'), server_default=sa.text("(N'midnight')"), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('phase_started_at', mssql.DATETIME2(), autoincrement=False, nullable=True))
    op.add_column('focus_sessions', sa.Column('phase_elapsed_seconds', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('difficulty_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('focus_sessions', sa.Column('break_minutes', sa.INTEGER(), server_default=sa.text('((5))'), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('focus_method', sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'), server_default=sa.text("('pomodoro')"), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('planned_cycles', sa.INTEGER(), server_default=sa.text('((1))'), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('auto_start_breaks', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('energy_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('focus_sessions', sa.Column('auto_start_focus', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('completed_cycles', sa.INTEGER(), server_default=sa.text('((0))'), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('current_cycle', sa.INTEGER(), server_default=sa.text('((1))'), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('ambient_sound', sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'), server_default=sa.text("(N'none')"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_focus_sessions_user_id'), table_name='focus_sessions')
    op.drop_index(op.f('ix_focus_sessions_task_id'), table_name='focus_sessions')
    op.drop_index(op.f('ix_focus_sessions_status'), table_name='focus_sessions')
    op.create_index(op.f('IX_focus_sessions_user_id'), 'focus_sessions', ['user_id'], unique=False)
    op.create_index(op.f('IX_focus_sessions_task_id'), 'focus_sessions', ['task_id'], unique=False)
    op.create_index(op.f('IX_focus_sessions_status'), 'focus_sessions', ['status'], unique=False)
    op.alter_column('focus_sessions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysutcdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('focus_sessions', 'completed_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'started_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=True)
    op.alter_column('focus_sessions', 'distraction_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    op.alter_column('focus_sessions', 'status',
               existing_type=sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'),
               server_default=sa.text("('running')"),
               existing_nullable=False)
    op.alter_column('focus_sessions', 'elapsed_seconds',
               existing_type=sa.INTEGER(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    op.alter_column('focus_sessions', 'actual_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('((0))'),
               existing_nullable=False)
    op.alter_column('focus_sessions', 'planned_minutes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('((25))'),
               existing_nullable=False)
    op.drop_constraint(None, 'focus_distractions', type_='foreignkey')
    op.drop_constraint(None, 'focus_distractions', type_='foreignkey')
    op.create_foreign_key(op.f('FK_focus_distractions_task'), 'focus_distractions', 'tasks', ['converted_task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('FK_focus_distractions_session'), 'focus_distractions', 'focus_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_focus_distractions_user_id'), table_name='focus_distractions')
    op.drop_index(op.f('ix_focus_distractions_session_id'), table_name='focus_distractions')
    op.drop_index(op.f('ix_focus_distractions_converted_task_id'), table_name='focus_distractions')
    op.create_index(op.f('IX_focus_distractions_user_id'), 'focus_distractions', ['user_id'], unique=False)
    op.create_index(op.f('IX_focus_distractions_session_id'), 'focus_distractions', ['session_id'], unique=False)
    op.create_index(op.f('IX_focus_distractions_converted_task_id'), 'focus_distractions', ['converted_task_id'], unique=False)
    op.create_index(op.f('IX_focus_distraction_session'), 'focus_distractions', ['session_id'], unique=False)
    op.alter_column('focus_distractions', 'captured_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysutcdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.drop_index(op.f('ix_email_notification_logs_user_id'), table_name='email_notification_logs')
    op.drop_index(op.f('ix_email_notification_logs_unique_key'), table_name='email_notification_logs')
    op.drop_index(op.f('ix_email_notification_logs_task_id'), table_name='email_notification_logs')
    op.drop_index(op.f('ix_email_notification_logs_project_id'), table_name='email_notification_logs')
    op.create_index(op.f('IX_email_notification_logs_user_id'), 'email_notification_logs', ['user_id'], unique=False)
    op.create_index(op.f('IX_email_notification_logs_task_id'), 'email_notification_logs', ['task_id'], unique=False)
    op.create_index(op.f('IX_email_notification_logs_project_id'), 'email_notification_logs', ['project_id'], unique=False)
    op.alter_column('email_notification_logs', 'sent_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysutcdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('email_notification_logs', 'status',
               existing_type=sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'),
               server_default=sa.text("('sent')"),
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_task_suggestions_note_id'), table_name='ai_task_suggestions')
    op.drop_index(op.f('ix_ai_task_suggestions_created_task_id'), table_name='ai_task_suggestions')
    op.drop_index(op.f('ix_ai_task_suggestions_analysis_id'), table_name='ai_task_suggestions')
    op.create_index(op.f('IX_ai_task_suggestions_note_id'), 'ai_task_suggestions', ['note_id'], unique=False)
    op.create_index(op.f('IX_ai_task_suggestions_analysis_status'), 'ai_task_suggestions', ['analysis_id', 'status'], unique=False)
    op.create_index(op.f('IX_ai_task_suggestions_analysis_id'), 'ai_task_suggestions', ['analysis_id'], unique=False)
    op.alter_column('ai_task_suggestions', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('ai_task_suggestions', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('(sysdatetime())'),
               type_=mssql.DATETIME2(),
               existing_nullable=False)
    op.alter_column('ai_task_suggestions', 'status',
               existing_type=sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'),
               server_default=sa.text("('Pending')"),
               existing_nullable=False)
    op.alter_column('ai_task_suggestions', 'priority',
               existing_type=sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'),
               server_default=sa.text("('Medium')"),
               existing_nullable=False)
    op.create_table('focus_chat_messages',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.NVARCHAR(length=20, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('message', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('provider', sa.NVARCHAR(length=50, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('model', sa.NVARCHAR(length=100, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['focus_sessions.id'], name=op.f('FK_focus_chat_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('FK_focus_chat_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__focus_ch__3213E83F6E4D6268'))
    )
    op.create_index(op.f('IX_focus_chat_session'), 'focus_chat_messages', ['session_id'], unique=False)
    op.create_table('notes_legacy_phase6',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.NVARCHAR(length=150, collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('content', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('detected_modules', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('extracted_tasks', sa.NVARCHAR(collation='Latin1_General_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('FK__notes__project_i__18EBB532')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__notes__3213E83FC30C32BF'))
    )
    op.create_table('focus_preferences',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('daily_focus_goal', sa.INTEGER(), server_default=sa.text('((120))'), autoincrement=False, nullable=False),
    sa.Column('default_method', sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'), server_default=sa.text("(N'pomodoro')"), autoincrement=False, nullable=False),
    sa.Column('default_cycles', sa.INTEGER(), server_default=sa.text('((1))'), autoincrement=False, nullable=False),
    sa.Column('default_sound', sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'), server_default=sa.text("(N'none')"), autoincrement=False, nullable=False),
    sa.Column('default_theme', sa.NVARCHAR(length=30, collation='Latin1_General_CI_AS'), server_default=sa.text("(N'midnight')"), autoincrement=False, nullable=False),
    sa.Column('auto_start_breaks', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('auto_start_focus', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.Column('show_coach_prompts', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=False),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('(sysutcdatetime())'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('FK_focus_preferences_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_focus_preferences'))
    )
    op.drop_index(op.f('ix_document_ai_analyses_user_id'), table_name='document_ai_analyses')
    op.drop_index(op.f('ix_document_ai_analyses_document_id'), table_name='document_ai_analyses')
    op.drop_table('document_ai_analyses')
    # ### end Alembic commands ###
